export const UserService = {
  getUsersData() {
    return [
      {
        id: "1000",
        code: "LFT-5001",

        employee: {
          firstName: "Ankit Kumar Thakur ",
          lastName: "Thakur",
          image: "amyelsner.png",
        },
        description: "Software Engineer",
        image: "bamboo-watch.jpg",
        price: 7011711442,
        category: "Verification Department",
        quantity: 24,
        status: "ACTIVE",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1001",
        code: "nvklal433",
        name: "Abhishek Kumar Thakur",
        employee: {
          firstName: "Abhishek Kumar Thakur",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 8368654239,
        username: "thakurAbhishek",
        department: "IT Department",
        location: "Bangalore",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        name: "Rinku Jain",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "blue-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 2,
        status: "INACTIVE",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1003",
        code: "244wgerg2",
        name: "Hari Mohan Jha",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "blue-t-shirt.jpg",
        price: 29,
        category: "Clothing",
        quantity: 25,
        status: "HOLD",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1004",
        code: "h456wer53",
        name: "Arvind Singh Rajput",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "bracelet.jpg",
        price: 15,
        category: "Accessories",
        quantity: 73,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1005",
        code: "av2231fwg",
        name: "Rajkumar",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "brown-purse.jpg",
        price: 120,
        category: "Accessories",
        quantity: 0,
        status: "OUTOFSTOCK",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1006",
        code: "bib36pfvm",
        name: "Vivek Oberoi",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "chakra-bracelet.jpg",
        price: 32,
        category: "Accessories",
        quantity: 5,
        status: "INACTIVE",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        name: "Siddhant Chaturvedi",
        employee: {
          firstName: "Ioni Bowcher",
          lastName: "Thakur",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "galaxy-earrings.jpg",
        price: 34,
        category: "Accessories",
        quantity: 23,
        status: "HOLD",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1008",
        code: "vbb124btr",
        name: "Arjun Singh",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "game-controller.jpg",
        price: 99,
        category: "Electronics",
        quantity: 2,
        status: "INACTIVE",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1009",
        code: "cm230f032",
        name: "Nikita",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "gaming-set.jpg",
        price: 299,
        category: "Electronics",
        quantity: 63,
        status: "HOLD",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1010",
        code: "cm230f033",
        name: "Anjali Devi",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "gold-phone-case.jpg",
        price: 24,
        category: "Accessories",
        quantity: 0,
        status: "OUTOFSTOCK",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1011",
        code: "cm230f034",
        name: "Sunita Ji",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "green-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 23,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1012",
        code: "cm230f035",
        name: "Shashank",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 74,
        status: "HOLD",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1013",
        code: "cm230f036",
        name: "Shashwat",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "grey-t-shirt.jpg",
        price: 48,
        category: "Clothing",
        quantity: 0,
        status: "OUTOFSTOCK",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1014",
        code: "waas1x2as",
        name: "Gaurav Arora",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "headphones.jpg",
        price: 175,
        category: "Electronics",
        quantity: 8,
        status: "INACTIVE",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1015",
        code: "vb34btbg5",
        name: "Shalini Dubey",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "light-green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 34,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1016",
        code: "k8l6j58jl",
        name: "Mamta Shrivastav",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "lime-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 12,
        status: "HOLD",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1017",
        code: "k8l6j58jp",
        name: "Rekha Kumari Mehto",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "mini-speakers.jpg",
        price: 85,
        category: "Clothing",
        quantity: 42,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1018",
        code: "09zx9c0zc",
        name: "Sonam Bajwa",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "painted-phone-case.jpg",
        price: 56,
        category: "Accessories",
        quantity: 41,
        status: "HOLD",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1019",
        code: "mnb5mb2m5",
        name: "Vamika Gibbi",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "pink-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 63,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1020",
        code: "r23fwf2w3",
        name: "Sonam Baweja",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "pink-purse.jpg",
        price: 110,
        category: "Accessories",
        quantity: 0,
        status: "OUTOFSTOCK",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1021",
        code: "pxpzczo23",
        name: "Nira Fatehi",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "purple-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 6,
        status: "INACTIVE",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1022",
        code: "2c42cb5cb",
        name: "Neelam",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "purple-gemstone-necklace.jpg",
        price: 45,
        category: "Accessories",
        quantity: 62,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1023",
        code: "5k43kkk23",
        name: "Neetu Singh",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "purple-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 2,
        status: "INACTIVE",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1024",
        code: "lm2tny2k4",
        name: "Nidhi Sing",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "shoes.jpg",
        price: 64,
        category: "Clothing",
        quantity: 0,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1025",
        code: "nbm5mv45n",
        name: "Satish Dhwaan",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "sneakers.jpg",
        price: 78,
        category: "Clothing",
        quantity: 52,
        status: "HOLD",
        rating: 4,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1026",
        code: "zx23zc42c",
        name: "Pratima Singh Roy",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "teal-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 3,
        status: "INACTIVE",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1027",
        code: "acvx872gc",
        name: "Shayam Sing Roy",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "yellow-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 35,
        status: "HOLD",
        rating: 3,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1028",
        code: "tx125ck42",
        name: "Gargi",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "yoga-mat.jpg",
        price: 20,
        category: "Fitness",
        quantity: 15,
        status: "HOLD",
        rating: 5,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
      {
        id: "1029",
        code: "gwuby345v",
        name: "Shweta Dwivedi",
        employee: {
          firstName: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        description: "Product Description",
        image: "yoga-set.jpg",
        price: 20,
        category: "Fitness",
        quantity: 25,
        status: "HOLD",
        rating: 8,
        designation: "Software Engineer",
        emailID: "akankit114@gmail.com",
        phoneNumber: 7011711442,
        username: "thakurAnkit",
        department: "Verification",
        location: "Gurgaon",
        reportingManager: "Sachin Sharma",
        issuedAssets: 5,
        issuedLicence: 6,
        totalRaisedTickets: 10,
      },
    ];
  },

  getUsersMini() {
    return Promise.resolve(this.getUsersData().slice(0));
  },

  getUsersSmall() {
    return Promise.resolve(this.getUsersData().slice(0, 10));
  },

  getProducts() {
    return Promise.resolve(this.getUsersData());
  },

  getUsersWithOrdersSmall() {
    return Promise.resolve(this.getUsersWithOrdersData().slice(0, 10));
  },

  getUsersWithOrders() {
    return Promise.resolve(this.getUsersWithOrdersData());
  },
};
